name: 网站状态检查器

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 30 分钟运行一次
  workflow_dispatch: # 手动触发

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check Website Status
        env:
          TARGET_URL: "https://lele1894.tk"
        run: |
          echo "Checking website status for $TARGET_URL"
          python - <<EOF
          import requests
          from datetime import datetime

          url = "$TARGET_URL"
          try:
              response = requests.get(url, timeout=10)
              status_code = response.status_code
              if response.ok:
                  result = f"Website is UP. Status Code: {status_code}"
              else:
                  result = f"Website is DOWN. Status Code: {status_code}"
          except requests.RequestException as e:
              result = f"Website is DOWN. Error: {e}"

          timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
          log_message = f"[{timestamp}] {result}"

          print(log_message)

          # Append the result to a log file
          with open("website_status.log", "a") as log_file:
              log_file.write(log_message + "\\n")
          EOF

      - name: Commit and Push Logs
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add website_status.log
          git commit -m "Update website status log"
          git push
        continue-on-error: true
